# Generated by Django (initial)
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
                ('macros', models.JSONField(default=dict)),
                ('dining_court', models.CharField(blank=True, max_length=100, null=True)),
                ('station', models.CharField(blank=True, max_length=255, null=True)),
                ('meal_time', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'foods',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories_per_hour', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['dining_court'], name='idx_foods_dining_court'),
        ),
    ]
